### ISSUE TITLE
关于微调 SCIDPR 的数据

### ISSUE THREAD

**Issue by CuteMing** [gmftbyGMFTBY/science-llm#2]
请问一下，关于微调 SCIDPR  embedding 模型的数据是什么样的呢？ 查阅代码发现有一个 train.json 文件，包含['a']['q']属性，但并没有找到相关文件，可以公开一下训练数据或者数据格式吗？感谢！

**Comment by gmftbyGMFTBY** [comment]
数据来源为AI2公开的数据集: https://allenai.org/data/qasper
以及我们DataHammer实验室公开的数据集：https://huggingface.co/datasets/DataHammer/scimrc
我们实验室公开的数据集来源如下：http://arxiv.org/abs/2306.14149

欢迎使用和测试
