### ISSUE TITLE
微调 SCIDPR 的数据，可以放出训好的模型吗

### ISSUE THREAD

**Issue by hjing100** [gmftbyGMFTBY/science-llm#3]
发现有人说：
这个工作比较有趣，将SciDPR同现有的检索模型相对比，可以发现SciDPR模型显著提升了Evidence召回的准确度。
方便放出训练好的模型吗？想试试效果

**Comment by gmftbyGMFTBY** [comment]
我们的公开模型托管在huggingface上：https://huggingface.co/DataHammer/scidpr-ctx-encoder，欢迎使用
